### ISSUE TITLE
hdiff links diff against previous release by time, not version

### ISSUE THREAD

**Issue by bergmark** [haskell-CI/hackage-matrix-builder#16]
e.g. http://hdiff.luite.com/cgit/http-conduit/commit?id=2.0.0.10 shows the diff `2.1.0..2.0.0.10` instead of `2.0.0.9..2.0.0.10`. Not helpful.

**Comment by hvr** [comment]
While I can cgit show me the log-delta, i.e.

http://hdiff.luite.com/cgit/http-conduit/log/?qt=range&q=2.0.0.9..2.0.0.10

I haven't figured out yet how to get a diff/patch out of that... if this was gitweb or github I'd know how...

**Comment by hvr** [comment]
got it: http://hdiff.luite.com/cgit/http-conduit/diff/?id=2.0.0.9&id2=2.0.0.10

**Comment by bergmark** [comment]
Nice! I'll do the rest then.

**Comment by hvr** [comment]
...and I accidentally swapped the ids, 'id2' is supposed to be the older tag/commit-id
