### ISSUE TITLE
template-haskell isn't constrained to installed version

### ISSUE THREAD

**Issue by bergmark** [haskell-CI/hackage-matrix-builder#22]
This causes [the stack build to fail](http://matrix.hackage.haskell.org/package/stack#GHC-7.8/stack-1.0.0) on GHC 7.8 while normal users will see a No-IP.

**Comment by hvr** [comment]
Hrm... we explicitly made `template-haskell` reinstallable in Cabal... is TH really not reinstallable?

**Comment by bergmark** [comment]
I thought it was constrained to installed in Cabal because it wasn't reinstallable...

**Comment by bergmark** [comment]
It turns out it is reinstallable, I'm not sure if I ever tested this but I did notice this in my `~/.cabal/config` which would explain my confusion:

```
constraint: template-haskell installed
```

**Comment by hvr** [comment]
see also https://github.com/haskell/cabal/issues/4098
