### ISSUE TITLE
Order matrix versions with newest at top

### ISSUE THREAD

**Issue by danielcompton** [haskell-CI/hackage-matrix-builder#25]
On http://matrix.hackage.haskell.org/package/yesod the most recent versions are at the bottom of the page. These are most likely to be the versions people are interested in, so it could be good to invert the order and put the newest versions at the top?

I'm not sure whether you'd also want to invert the the order of the Haskell versions so they continue to ascend from left to right.

https://github.com/haskell/hackage-server/issues/502

**Comment by bergmark** [comment]
I'm not sure if reversing the order of GHC versions was a good idea as I find it confusing. But it might be that i'm used to the old ordering.

![screen shot 2016-06-03 at 14 20 44](https://cloud.githubusercontent.com/assets/100681/15778456/9bef2656-2996-11e6-863c-21c9eab5a59f.png)

**Comment by danielcompton** [comment]
I'm not too sure either, it does seem a little odd as the arrow of time if moving backwards.
