### ISSUE TITLE
Publicize breaking changes early

### ISSUE THREAD

**Issue by ghost** [haskell-CI/hackage-matrix-builder#31]
(I am not sure where to file this).

Maybe a collection of two tools:

1. Given a github repo, compare the tip of master's source code versus the last hackage release source, comparing public functions for signature changes.

2. A report, similar to packdeps website, which accumulates the result of running tool (1), crawling across hackage packages continuously.

The intention would be an early alert system for what might be coming in the next changelog, to reduce the delay between when a library author knows of an upcoming breaking change, and when a downstream user of the library discovers a breaking change is coming. Just an initial idea. Feel free to close or move this issue to somewhere else.

**Comment by hvr** [comment]
This requires the availability of static API analyzers (which are on the roadmap as they're essential to the grand master plan underlying the matrix builder project... that's all I'm gonna say right now :-) )

**Comment by ghost** [comment]
Okay, you can reopen later if applicable.

**Comment by hvr** [comment]
We can keep this open; I've created a new milestone for more long-term-ish things.
