### ISSUE TITLE
how to install extra system-libraries on the matrix building machines

### ISSUE THREAD

**Issue by cdepillabout** [haskell-CI/hackage-matrix-builder#50]
I have a package that is failing to build because the required system-libraries are not installed on the matrix building machines:

https://hackage.haskell.org/package/termonad-0.2.0.0/reports/

Is there some way to get extra system-libraries installed on the matrix building machines?

For instance, assuming that the build machines are running ubuntu, the `termonad` package requires the system packages `libvte-2.91-dev` and `libgtk-3-dev`.  Is there somewhere I can send a PR to add these?

As a comparison, the stackage server has a script that specifies which system-libraries will be available.  Here is a part of a PR where I added the `libvte-2.91-dev` library to it:

https://github.com/commercialhaskell/stackage/commit/d6baa99fd17cccad6a05db3df8192fa879b27fe2#diff-4895bf1f155502ab11cd1cee9e22f4ff

This lets the `termonad` be able to be built on stackage.

I thought that the Hackage Matrix Builder might have something similar, although I couldn't find anything during a quick look around this repo.

However, it is entirely possible that I am reporting this on the wrong issue tracker, so if there is a better place to report this, please let me know!

**Comment by hvr** [comment]
There's actually currently two builders, the doc-builder for hackage (cc @gbaz) and the hackage matrix builder (at some point they might be unified, but at this point they aren't)

For the matrix builder, there is such a list but it's not kept in the Git repository; I've added those two packages to the matrix builder now, but there's some internal issue (unrelated to `termonad`) that makes the matrix builder choke on version 0.2.0.0:

https://matrix.hackage.haskell.org/package/termonad

**Comment by cdepillabout** [comment]
@hvr Thanks a lot for your help!  That's great that termonad is now able to be built by the matrix builder!  Hopefully the problem with the matrix builder for termonad-0.2.0.0 will be worked-out.

I'd also really like the documentation to be generated automatically, so hopefully @gbaz (?) will be able to add the two packages listed above to the doc-builder machine as well.

Thanks a lot!

**Comment by cdepillabout** [comment]
@gbaz At some point in the next couple weeks I'd like to release an updated version of [termonad](https://github.com/cdepillabout/termonad) to Hackage.  It'd be great to have `libvte-2.91-dev` and `libgtk-3-dev` available on the machine that builds Hackage documentation.  Is there some way I can speed up this process of adding these packages?

**Comment by hvr** [comment]
@cdepillabout btw, if you upload to hackage and the doc-builder fails to generate docs due to missing deps, you can file an issue at https://github.com/haskell-infra/hackage-trustees/issues/new and then a Trustee can step in and generate docs (assuming the FFI deps are easy to install on mainstream linux distros)

**Comment by cdepillabout** [comment]
@hvr Thanks for the info!  I've posted an issue:

https://github.com/haskell-infra/hackage-trustees/issues/184

I'll go ahead and close this issue since you already installed the two given packages for me in https://github.com/haskell-CI/hackage-matrix-builder/issues/50#issuecomment-413772206.  Thanks for your help!
