### ISSUE TITLE
vector builds stuck enqueued?

### ISSUE THREAD

**Issue by cartazio** [haskell-CI/hackage-matrix-builder#70]
https://matrix.hackage.haskell.org/ng/#/package/vector

<img width="1191" alt="Screen Shot 2020-02-01 at 2 25 54 PM" src="https://user-images.githubusercontent.com/4290/73597861-d12d2480-44fe-11ea-9187-4433eac5c0d7.png">

**Comment by hvr** [comment]
I believe this had the same underlying issue as #73 and has been since resolved
